/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DoblePassword;

import java.awt.Color;

/**
 *
 * @author Manana
 */
public class DoblePassword extends javax.swing.JPanel {

    /**
     * Creates new form DoblePassword
     */
    public DoblePassword() {
        initComponents();
            
        jpasswd1.setText("");
        jpasswd2.setText("");
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpasswd1 = new javax.swing.JPasswordField();
        jpasswd2 = new javax.swing.JPasswordField();
        validatelbl = new javax.swing.JLabel();

        jpasswd1.setText("jPasswordField1");

        jpasswd2.setText("jPasswordField2");
        jpasswd2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpasswd2FocusLost(evt);
            }
        });

        validatelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpasswd1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jpasswd2, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpasswd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpasswd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(validatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jpasswd2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpasswd2FocusLost
        String contrasena1 = new String(jpasswd1.getPassword());
        String contrasena2 = new String(jpasswd2.getPassword());
        
        
        if(contrasena1.isEmpty()){
            return;
        }
        
        if (contrasena1.equals(contrasena2)) {
            validatelbl.setText("T");
            validatelbl.setForeground(Color.GREEN);
        } else {
            validatelbl.setText("F");
            validatelbl.setForeground(Color.RED);
        }
    }//GEN-LAST:event_jpasswd2FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jpasswd1;
    private javax.swing.JPasswordField jpasswd2;
    private javax.swing.JLabel validatelbl;
    // End of variables declaration//GEN-END:variables
}
