/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen;

import java.awt.Point;
import java.awt.event.MouseEvent;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import examen.comboBoxWidget;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.util.Random;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Manana
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Point puntoPopUp;
    private BufferedImage imagen;
    
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
      
      annadirComboBox();
      configurarRendererTemperaturas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        menuItemInsertar = new javax.swing.JMenuItem();
        menuItemEliminar = new javax.swing.JMenuItem();
        menuItemSeleccTodo = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("examen/VentanaPrincipal"); // NOI18N
        menuItemInsertar.setText(bundle.getString("INSERTAR")); // NOI18N
        menuItemInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInsertarActionPerformed(evt);
            }
        });
        popupMenu.add(menuItemInsertar);

        menuItemEliminar.setText(bundle.getString("ELIMINAR")); // NOI18N
        menuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarActionPerformed(evt);
            }
        });
        popupMenu.add(menuItemEliminar);

        menuItemSeleccTodo.setText(bundle.getString("SELECCIONAR TODO")); // NOI18N
        menuItemSeleccTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSeleccTodoActionPerformed(evt);
            }
        });
        popupMenu.add(menuItemSeleccTodo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Salamanca", "01/02/2025", "12"},
                {"Salamanca", "02/03/2025", "16"},
                {"Salamanca", "03/04/2025", "20"},
                {"Salamanca", "04/05/2025", "24"},
                {"Salamanca", "05/06/2024", "30"},
                {"Ávila", "01/02/2025", "10"},
                {"Ávila", "02/03/2025", "14"},
                {"Ávila", "03/04/2025", "19"},
                {"Ávila", "04/05/2025", "22"},
                {"Ávila", "05/06/2024", "27"},
                {"Zamora", "01/02/2025", "14"},
                {"Zamora", "02/03/2025", "18"},
                {"Zamora", "03/04/2025", "22"},
                {"Zamora", "04/05/2025", "27"},
                {"Zamora", "05/06/2024", "32"}
            },
            new String [] {
                "Localidad", "Fecha", "Temperatura Max (ºC)"
            }
        ));
        tabla.setComponentPopupMenu(popupMenu);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMouseClicked(evt);
            }
        });

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen/Mapa Castilla y Leon.png"))); // NOI18N
        lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(lblImagen)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("examen/VentanaPrincipal").getString("DESEAS ELIMINAR ESTOS CAMPOS?"), java.util.ResourceBundle.getBundle("examen/VentanaPrincipal").getString("DESEAS ELIMINAR LOS CAMPOS SELECCIONADOS?"), JOptionPane.YES_NO_OPTION);
        
        if(respuesta == JOptionPane.YES_OPTION){
            int [] filas = tabla.getSelectedRows();
        if(filas.length>0){
            for(int i = filas.length-1; i>=0; i--){
            ((DefaultTableModel)tabla.getModel()).removeRow(filas[i]);
            }
        }
        }
    }//GEN-LAST:event_menuItemEliminarActionPerformed

    private void menuItemSeleccTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSeleccTodoActionPerformed
        tabla.selectAll();
    }//GEN-LAST:event_menuItemSeleccTodoActionPerformed

    private void menuItemInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInsertarActionPerformed
       int filaSeleccionada = tabla.rowAtPoint(puntoPopUp);
    
    if (filaSeleccionada != -1) { 
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.insertRow(filaSeleccionada + 1, new Object[tabla.getColumnCount()]);
    } else {
        JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("examen/VentanaPrincipal").getString("NO SE HA SELECCIONADO NINGUNA FILA."), 
            java.util.ResourceBundle.getBundle("examen/VentanaPrincipal").getString("ADVERTENCIA"), JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_menuItemInsertarActionPerformed

    private void tablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseReleased
        
    }//GEN-LAST:event_tablaMouseReleased

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
       puntoPopUp = evt.getPoint();
    }//GEN-LAST:event_tablaMousePressed

    private void lblImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenMouseClicked
Graphics gVentana = lblImagen.getGraphics();
gVentana.setColor(Color.ORANGE);
gVentana.fillOval(evt.getX(), evt.getY(), 15, 15);
gVentana.drawLine(evt.getX()+15, evt.getY()+15, evt.getX()+15, evt.getX()-20);
gVentana.drawLine(evt.getX()+20, evt.getY()+7, evt.getX()-5, evt.getX()+7);
    }//GEN-LAST:event_lblImagenMouseClicked

    private void jPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMouseClicked

    }//GEN-LAST:event_jPanelMouseClicked
    
    private void annadirComboBox(){
        tabla.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(new comboBoxWidget()));
    }
    
    private void configurarRendererTemperaturas() {
    tabla.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable tabla, 
                Object value, boolean isSelected, boolean hasFocus, 
                int row, int column) {


            Component c = super.getTableCellRendererComponent(tabla, value, 
                    isSelected, hasFocus, row, column);


            if (!isSelected) {
                if (column == 2) {

                    String tempStr = tabla.getValueAt(row, 2).toString();
                    double temp = Double.parseDouble(tempStr);


                    if (temp > 30) {
                        c.setBackground(Color.RED);
                    } else if (temp >= 20) {

                        c.setBackground(Color.ORANGE);
                    } else {

                        c.setBackground(Color.BLUE);
                    }
                    setForeground(Color.WHITE); 
                } else {

                    c.setBackground(Color.WHITE);
                    c.setForeground(Color.BLACK);
                }
            } else {

                c.setBackground(tabla.getSelectionBackground());
                c.setForeground(tabla.getSelectionForeground());
            }

            return c;
        }
    });
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (java.util.ResourceBundle.getBundle("examen/VentanaPrincipal").getString("NIMBUS").equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JMenuItem menuItemEliminar;
    private javax.swing.JMenuItem menuItemInsertar;
    private javax.swing.JMenuItem menuItemSeleccTodo;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
