/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package u4Layouts.ejercicios;


import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JToggleButton;

/**
 *
 * @author Manana
 */
public class JuegoMemoria extends javax.swing.JFrame {
    
    private final int NUM_CARTAS = 16;
    private ArrayList<Color> colores;
    private ArrayList<JToggleButton> cartas;
   
    
    
    /**
     * Creates new form JuegoMemoria
     */
    public JuegoMemoria() {
        
        initComponents();
        iniciarCartas();
        pack();
        setLocationRelativeTo(null);
    }
    
    private void iniciarCartas(){
        
        Color[] coloresBase = {
            Color.RED, Color.BLUE, Color.GREEN, Color.YELLOW,
            Color.ORANGE, Color.PINK, Color.CYAN, Color.MAGENTA
        };
        
        
        // Duplicar los colores para hacer parejas
        colores = new ArrayList<>();
        for(Color color : coloresBase){
            colores.add(color);
            colores.add(color); 
        }
        
        Collections.shuffle(colores); // Para mezclar los colores
        
        cartas = new ArrayList();
        
        //jPanel1.setMinimumSize(new Dimension(50,50)); // Para darle tamaño inicial a la ventana.
        for(int i=0; i<NUM_CARTAS; i++){
            JToggleButton carta = new JToggleButton();
            carta.setPreferredSize(new Dimension(50, 50)); // Tamaño preferido
            carta.setOpaque(true);
            carta.setBackground(Color.GRAY);
            
            int index = i;
            
            carta.addActionListener(e -> mostrarColor(carta, index));

            cartas.add(carta);
            jPanel1.add(carta); // Para añadir los jtb al jpanel.
        }   
    }
    private void mostrarColor(JToggleButton carta, int index) {
        // Muestra el color asociado a la carta cuando se selecciona
        carta.setBackground(carta.isSelected() ? colores.get(index) : null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 4));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoMemoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
