/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package u2Ejercicios;

import com.formdev.flatlaf.FlatDarkLaf;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Manana
 */
public class RefuerzoCuadrosDialogo extends javax.swing.JFrame {

    /**
     * Creates new form RefuerzoCuadrosDialogo
     */
    public RefuerzoCuadrosDialogo() {
        initComponents();
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RefuerzoCuadrosDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RefuerzoCuadrosDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RefuerzoCuadrosDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RefuerzoCuadrosDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                UIManager.setLookAndFeel( new FlatDarkLaf() );
            } catch( UnsupportedLookAndFeelException ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
                new RefuerzoCuadrosDialogo().setVisible(true);
                jugarAdivinarNumero();
            }
        });
    }
    private static void jugarAdivinarNumero() {
        Random rd = new Random();
        int numeroAdivinar = rd.nextInt(10) + 1;

        boolean boo = false;
        while (!boo) {
            String respuestaStr = JOptionPane.showInputDialog(null, "Adivina el número (1-10):", "Adivina el número", JOptionPane.QUESTION_MESSAGE);
            if (respuestaStr == null) {
                int salir = JOptionPane.showConfirmDialog(null, "¿Quieres salir del juego?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (salir == JOptionPane.YES_OPTION) {
                    break;
                } else {
                    continue;
                }
            }

            try {
                int respuesta = Integer.parseInt(respuestaStr);
                if (respuesta < 1 && respuesta > 10) {
                    JOptionPane.showMessageDialog(null, "Por favor, introduce un número entre 1 y 10.", "Vaya tela", JOptionPane.WARNING_MESSAGE);
                } else if (respuesta < numeroAdivinar) {
                    JOptionPane.showMessageDialog(null, "El número es mayor.", "Tontin", JOptionPane.INFORMATION_MESSAGE);
                } else if (respuesta > numeroAdivinar) {
                    JOptionPane.showMessageDialog(null, "El número es menor.", "Tontin", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "¡Felicidades! Has adivinado el número.", "Grande genio", JOptionPane.INFORMATION_MESSAGE);
                    int jugarDeNuevo = JOptionPane.showConfirmDialog(null, "¿Quieres volver a jugar?", "Échale huevos", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (jugarDeNuevo == JOptionPane.YES_OPTION) {
                        numeroAdivinar = rd.nextInt(10) + 1;
                    } else {
                        boo = true;
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Entrada inválida. Por favor, introduce un número.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

